openapi: 3.0.3
info:
  title: Bug Survivors Backend
  description: |-
    Backend API for Bug Survivors
  version: 0.0.1
externalDocs:
  description: API of ya-praktikum.tech
  url: https://ya-praktikum.tech/api/v2/swagger/
servers:
  - url: http://localhost:3002/api/v2
tags:
  - name: emoji
    description: Emoji on comment
paths:
  /emoji/{commentId}:
    get:
      tags:
        - emoji
      operationId: getEmojiByCommentId
      summary: Get comment emoji
      description: Get emoji by comment ID
      parameters:
        - name: commentId
          in: path
          description: 'The comment which need fetch emoji'
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEmoji'
        '400':
          description: Invalid commentId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden (Not Authorized)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - emoji
      summary: Update comment emoji
      description: Update emoji by commentId
      operationId: updateEmoji
      parameters:
        - name: commentId
          in: path
          description: 'The comment which needs update emoji'
          required: true
          schema:
            type: number
      requestBody:
        description: Update an existent emoji in database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateEmoji'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEmoji'
        '400':
          description: Invalid comment ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden (Not Authorized)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Emoji:
      type: string
      example: '😄'

    ResponseEmoji:
      type: array
      items:
        type: object
        properties:
          count:
            type: number
            format: int64
            example: 55
          emoji:
            $ref: '#/components/schemas/Emoji'

    RequestUpdateEmoji:
      type: object
      properties:
        userId:
          type: number
          format: int64
        commentId:
          type: number
          format: int64
          example: 2
        emoji:
          $ref: '#/components/schemas/Emoji'
    Error:
      type: object
      properties:
        status:
          type: number
          format: int64
          example: 400

        message:
          type: string
          format: string
          example: Something wrong...
