version: '3.9'

services:
  postgres:
    image: postgres:14
    env_file:
      - './.env'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - awesome

  server:
    container_name: prakticum-server
    image: prackicum-server
    env_file:
      - './.env'
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgres
    networks:
      - awesome

  client:
    container_name: prakticum-client
    image: prakticum-client
    env_file:
      - './.env'
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    depends_on:
      - postgres
      - server

networks:
  awesome:
    driver: bridge
